language: go
dist: trusty
sudo: required
install: true
go:
  - 1.7.1
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.1
before_install:
  - sleep 15
  - sudo apt-get install -y
  - sudo apt-get install -y curl
  - go env && pwd
  - mkdir -p $HOME/gopath/bin
  - echo deb https://apt.dockerproject.org/repo ubuntu-`lsb_release -c | awk '{print $2}'` main | sudo tee /etc/apt/sources.list.d/docker.list
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-get install -y docker-engine
  - sudo service docker restart
  - docker version
  - id
script:
  - make build

